### ISSUE TITLE
README still mentions built files

### ISSUE THREAD

**Issue by arkon** [gmusic-utils/gmusic.js#13]
The README mentions that you can use the library by just linking to the built file from here on GitHub, but the contents of `dist/` aren't actually here.

**Comment by jostrander** [comment]
That's actually for an older version and should be amended to not say that. When we ported to es6 we decided that storing dist in git was a bad idea.

**Comment by bichotll** [comment]
So what's the story with bower?
Bower.json has not been updated since 5.X. Also, releases does not have build folder either.

Unfortunately, I'm still using bower...:/

**Comment by MarshallOfSound** [comment]
> Unfortunately, I'm still using bower...:/

`bower` is not a supported install method anymore, due to use not storing the dist in version control

**Comment by x3haloed** [comment]
Since we can't download the built version from dist anymore, can you please provide up-to-date build/transpile instructions? I tried to guess now it should work, but I couldn't figure it out. I installed gulp and babel, and I ran `gulp build`, but babel threw an error about the syntax in gmusic.js being wrong.

**Comment by arkon** [comment]
What exactly is the syntax error?

**Comment by jostrander** [comment]
You should be able to run `npm run build` after a fresh clone, but I would like to see the syntax error as well.

**Comment by arkon** [comment]
On a related note, I think the bower instructions should be removed as well, based on the past conversation here.

**Comment by jostrander** [comment]
PR? ;)

**Comment by x3haloed** [comment]
Running `npm install` and `npm run build` on a fresh clone worked. I must have messed up the babel config before.

Thank you for your help!
