### ISSUE TITLE
Add new I'm Feeling Lucky API

### ISSUE THREAD

**Issue by MarshallOfSound** [gmusic-utils/gmusic.js#16]
With the new placement of the I'm Feeling Lucky button, it will probably be possible to add an API to trigger it 👍

**Comment by MarshallOfSound** [comment]
Thinking something like `playback.startFeelingLucky()`

**Comment by arkon** [comment]
I'm not sure if this is feasible since it's only on the home page?

**Comment by jostrander** [comment]
You are right, its not available unless you're on the home page.
