### ISSUE TITLE
Use libraries without npm

### ISSUE THREAD

**Issue by aazimh** [gmusic-utils/gmusic.js#19]
Hi guys,

Might be a stupid question as I'm not super experienced with JavaScript, but is it possible to use this and the gmusic-ui libraries without installing via npm, i.e. just downloading the JS files or possibly inserting them as scripts in my HTML? I notice the gmusic-ui README has this option but the link it mentions is broken so that doesn't really work. I'd appreciate any help I can get!

Thanks a lot,
Aazim.

**Comment by MarshallOfSound** [comment]
As of V6 we only support installation through NPM, if you want the script file you can clone and build from source 👍

**Comment by aazimh** [comment]
Fair enough - realized that was for Node, I can use the Websockets to call the methods so I'm good :) thank you!

On another note, the 'getVolume' function seems to return 'undefined' instead of the current volume - is this a known issue? My call is:

```
var command = {"namespace":"volume", "method":"getVolume"};
var curvol = ws.send(JSON.stringify(command));
```

**Comment by aazimh** [comment]
Never mind, just seen you need to pass requestID - ignore me. Thanks for all the awesome work!

**Comment by aazimh** [comment]
Okay no, still doesn't work. Here's my code:

```
var command = {"namespace":"volume", "method":"getVolume", "requestID":56};
var curvol = ws.send(JSON.stringify(command));
alert(curvol);
```

Still returns 'undefined'. Let me know if you have any tips on this.
