### ISSUE TITLE
Failed to find progress element for function PlaybackNamespace()

### ISSUE THREAD

**Issue by jacktang** [gmusic-utils/gmusic.js#20]
Hello,

I play with GMusic in Chrome devtools console, and the code `window.GPM = new GMusic();` throws the error: Failed to find progress element for function PlaybackNamespace(). What should I do to fix the error?

BR

**Comment by MarshallOfSound** [comment]
You are probably trying to initialize GMusic on a page without a progress bar or you are initializing it too early.  You normally need to wait for GPM to fully load before initializing GMusic

**Comment by jacktang** [comment]
@MarshallOfSound I tried the same code snippet in GoogleMusicPlayerDesktop dev console, it threw the same error. The page and progress bar were fully load. See screenshot:  

![GooglePlayerDesktop](https://pbs.twimg.com/media/DDZGw5IVYAU5krx.jpg)

**Comment by MarshallOfSound** [comment]
Oh, you're running that in the wrong console.  If you're in GPMDP run the function `window.openGPMDevTools()` and run it in that console 👍

**Comment by jacktang** [comment]
Thanks! it works now :)
