### ISSUE TITLE
Lyrics autoscroll jumps

### ISSUE THREAD

**Issue by breatheloud** [gmusic-utils/gmusic.js#23]
Don't get me wrong I really appreciate that the lyrics scroll by themselves, but it often starts too early or is too slow (and other times too fast).  Once the lyrics have hit the end of the song the subsequent songs' lyrics don't scroll and jump/flash to the end of the lyrics of the next song (though on load, the first few lines of the lyrics are visible momentarily).  

I recommend giving the user the option to disable (and re-enable) auto scroll and thus enable manual scrolling on the lyrics overlay, until the bug can be squashed.

I'm using Mac OS El Capitan (10.11.6) on a Macbook Pro Mid-2015 15"
Just updated to 4.4.1 of the app

**Comment by jostrander** [comment]
This isn't part of this repo, and it's already been implemented as an option in GPMDP.

**Comment by breatheloud** [comment]
My bad, I was thinking of something more of an overlay when the lyrics screen pops up.  Didn't realise it was in settings/preferences.  Thanks
