### ISSUE TITLE
Remove `twolfson` from Travis CI notifications

### ISSUE THREAD

**Issue by twolfson** [gmusic-utils/gmusic.js#4]
It looks like I'm still configured to receive build notifications for this repo from Travis CI. Could you please update those away from my email address? (I would submit a PR but not sure if you want full disabling or new emails =/)

https://github.com/gmusic-utils/gmusic.js/blob/a6c3d928c2ebd6d9e9169e64aacc7d9dbdcecbac/.travis.yml#L21

**Comment by jostrander** [comment]
@gmusic-utils/gmusic-js What's the consensus on this? Who wants to be emailed? @MarshallOfSound?

**Comment by MarshallOfSound** [comment]
![200_s](https://cloud.githubusercontent.com/assets/6634592/17196964/c90295b6-54ab-11e6-8440-86887933cfce.gif)

**Comment by twolfson** [comment]
I received another email again today. Can we get this patched? =/

**Comment by MarshallOfSound** [comment]
Sorry, thought this had been dealt with

**Comment by twolfson** [comment]
Sweet, thanks @MarshallOfSound :+1:
