### ISSUE TITLE
Shuffle selector returns two results in album view

### ISSUE THREAD

**Issue by Meegooo** [gmusic-utils/gmusic.js#6]
When you are viewing an album and invoke [this](https://github.com/gmusic-utils/gmusic.js/blob/master/src/namespaces/PlaybackNamespace.js#L123) method, it clicks the shuffle button on top, not the one on the bottom. 
Both those buttons have the same attribute (`data-id="shuffle"`) and button on top is the first and is the one being clicked

Source of this bug https://github.com/GPMDP/google-play-music-desktop-remote/issues/5

**Comment by MarshallOfSound** [comment]
Lol, just found this issue myself on the Playlist view
